baseURL = "https://mayabot.github.io/mynlp-doc/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Mynlp文档"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = ""

    github_repository = "https://github.com/mayabot/mynlp"
    version = "3.1.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = ""

    # Analytic section
    google_analytics_id = "UA-388690-17" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    #title = "Hugo Techdoc Theme"
    #images = ["og-image.png"]
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards

    # Theme settings section
    # Theme color
    custom_font_color = "#ededed"
    custom_background_color = "#142850"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "2006-01-02" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
        "sample"
    ]

# Global menu section
        [[menu.main]]
    name = "Mynlp文档"
    url = "https://mynlp.mayabot.com/"
    weight = 1
    pre= "<i class='fab fa-github'></i>"

[[menu.main]]
    name = "在线演示"
    url = "/demo"
    weight = 2

[[menu.main]]
    name = "博客"
    url = "http://blog.mayabot.com"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true
